name: learners_gateway
description: A Flutter web application for teaching coding and tech knowledge
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^14.0.0
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.2.0
  visibility_detector: ^0.2.2

  # Firebase - WEB COMPATIBLE VERSIONS
  firebase_core: ^2.24.1
  firebase_auth: ^4.17.1
  cloud_firestore: ^4.13.0
  firebase_storage: ^11.5.6

  # State Management
  provider: ^6.1.1

  # Remove these temporarily to fix Firebase issues
  # image_picker: ^1.0.4
  # file_picker: ^5.2.6

  # UUID for unique IDs
  uuid: ^4.3.3

  # Date formatting
  intl: ^0.19.0

  # Share functionality
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/